# Fixed: MySQL amb configuracio segura
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y mysql-server

RUN useradd -m -u 1001 appuser

# Configuracio segura: nomes connexions locals
RUN sed -i 's/bind-address.*/bind-address = 127.0.0.1/' /etc/mysql/mysql.conf.d/mysqld.cnf

# Usuari amb contrasenya forta i privilegis minims
RUN service mysql start && \
    mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'R00t_S3cur3!2024';" && \
    mysql -e "DELETE FROM mysql.user WHERE User='';" && \
    mysql -e "DELETE FROM mysql.user WHERE Host!='localhost';" && \
    mysql -e "DROP DATABASE IF EXISTS test;" && \
    mysql -e "FLUSH PRIVILEGES;" && \
    mysql -e "CREATE DATABASE app_db;" && \
    mysql -e "CREATE USER 'appuser'@'localhost' IDENTIFIED BY 'App_S3cur3!2024';" && \
    mysql -e "GRANT SELECT, INSERT, UPDATE ON app_db.* TO 'appuser'@'localhost';" && \
    mysql -e "FLUSH PRIVILEGES;"

EXPOSE 3306

CMD ["mysqld_safe"]
